#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index

# Use sed to modify the Nginx configuration file and create a permanent redirect for /redirect_me
sudo sed -i '/location \/ {/a \\n\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

sudo service nginx restart
