#!/usr/bin/env bash
# Installs haproxy load balancer
# Set backend using roundrobin algorithm
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 36882-web-01 34.202.159.128:80 check\n\tserver 36882-web-02 54.237.71.141:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
