#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx start
sudo pkill -o nginx
